### ISSUE TITLE
Identify which boilerplate to base fast-electron-boilerplate on

### ISSUE THREAD

**Issue by andrewschreiber** [andrewschreiber/electron-rspack#10]
### What problem does this feature solve?

We want to create a new boilerplate, but need to test existing good options.

https://github.com/cawa-93/vite-electron-builder
https://github.com/electron-react-boilerplate/electron-react-boilerplate
https://github.com/alex8088/electron-vite-boilerplate
https://github.com/electron/electron-quick-start

**Comment by andrewschreiber** [comment]
Next steps:
- For each boilerplate, install with typescript + react. 
  - Test that the boilerplate runs.
  - Add app.exit() to the end of the main process initialization (see package.json entrypoint var to find file main.ts / index.ts usually). 
  - Test that the app auto quits immediately
  - Run Hyperfine to measure total launch + quit speed and note that speed. `hyperfine --warmup 1 --runs 3 -N "[start command here]"` ie `hyperfine --warmup 1 --runs 3 -N "npm start"`
  
For https://github.com/cawa-93/vite-electron-builder this is 1.53 seconds

**Comment by andrewschreiber** [comment]
<img width="512" alt="image" src="https://github.com/user-attachments/assets/28d18e4f-b31f-4e21-8f02-87518a5caa0e" />

Running on Mac. On `npm run start`, I exited after mainWindow.show() with `process.kill(process.ppid, 'SIGTERM')` in order to also kill the electronmon watcher.

**Comment by kombofuud** [comment]
vite electron builder:
build: 5.401 s ±  0.130 s
install: 7.663 +- 0.285
start: 5.91 +- 0.834

electron react boilerplate:
build: 7.643 s ±  0.362 s
install: 11.558 s ±  0.213 s 
start: 13.490 s ±  0.184 s

electron-vite-boilerplate:
build: 6.955 s ±  0.105 s
install: 2.482 s ±  0.031 s
start: 2.424 s ±  0.117 s

electron-quick-start:
build: N/A
install: N/A
start: 2.212 +- 0.103

**Comment by andrewschreiber** [comment]
I tested on npm run dev pre-window launch and got a similar hierarchy

electron-vite-boilerplate is the winner!
